include $(srctree)/drivers/misc/mediatek/Makefile.custom

# In case the platform does NOT support this type of sensors

obj-y   +=  accel.o accel_factory.o

obj-y   +=  bmi160_acc/
obj-y   +=  lsm6ds3/
obj-y   +=  bmi160_stc/
